apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
data:
  cinder.conf: |+
{{ tuple "etc/_cinder.conf.tpl" . | include "template" | indent 4 }}
  api-paste.ini: |+
{{ tuple "etc/_cinder-api-paste.ini.tpl" . | include "template" | indent 4 }}
  policy.json: |+
{{ tuple "etc/_policy.json.tpl" . | include "template" | indent 4 }}
  ceph.conf: |+
{{ tuple "etc/_ceph.conf.tpl" . | include "template" | indent 4 }}
  ceph.client.{{ .Values.ceph.cinder_user }}.keyring: |+
{{ tuple "etc/_ceph-cinder.keyring.tpl" . | include "template" | indent 4 }}
  ceph.client.{{ .Values.ceph.admin_user }}.keyring: |+
{{ tuple "etc/_ceph-admin.keyring.tpl" . | include "template" | indent 4 }}
  ceph.client.{{ .Values.ceph.glance_user }}.keyring: |+
{{ tuple "etc/_ceph-glance.keyring.tpl" . | include "template" | indent 4 }}
